version: "3"
services:
  lavalink:
    image: fredboat/lavalink:master-v3
    ports:
      - "2333:2333"
    volumes:
      - "./lavalink/application.yml:/opt/Lavalink/application.yml"
  redis:
    image: redis
    restart: always
    ports:
      - "2334:6379"
